USE [LCLTD]
GO
/****** Object:  StoredProcedure [dbo].[ALB_WMS_PROCESS_ORDER_PICKING_CLOSE_QUEUE]    Script Date: 3/3/2021 11:18:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[ALB_WMS_PROCESS_ORDER_PICKING_CLOSE_QUEUE]

AS
DECLARE @SOPTYPE INT
DECLARE @SOPNUMBE VARCHAR(25)
DECLARE @USERID VARCHAR(15)
DECLARE @DATEREQUESTED DATETIME
DECLARE @TIMEREQUESTED DATETIME
DECLARE @STATUS INT
DECLARE @LOCNCODE VARCHAR(15)
DECLARE @BIN VARCHAR(15)
DECLARE @SLTSQNUM INT
DECLARE @ORIGSLTSQNUM INT
DECLARE @TOTALSERLTQTY NUMERIC (19, 5)
DECLARE @CURRENTQTY NUMERIC (19, 5)
DECLARE @SERLTQTY NUMERIC (19, 5)
DECLARE @NEWQTY NUMERIC (19, 5)
DECLARE @ITEMNMBR VARCHAR(31)
DECLARE @LNITMSEQ INT
DECLARE @CMPNTSEQ INT
DECLARE @SERLTNUM VARCHAR(21)
DECLARE @DATERECD DATETIME
DECLARE @DTSEQNUM NUMERIC (19, 5)
DECLARE @QUANTITY NUMERIC (19, 5)
DECLARE @CASECOUNT NUMERIC (19, 5)
DECLARE @AVERAGEWEIGHT NUMERIC (19, 5)
DECLARE @COUNT INT
DECLARE @CWQUANTITY NUMERIC (19, 5)
DECLARE @QTYREMAI NUMERIC (19, 5)
DECLARE @CWQTYREMAI NUMERIC (19, 5)
DECLARE @QTYDEALLOCATED NUMERIC (19, 5)
DECLARE @QTYCREATED NUMERIC (19, 5)

DECLARE @SUBTOTAL NUMERIC (19, 5)
DECLARE @ORSUBTOTAL NUMERIC (19, 5)
DECLARE @REMSUBTOTAL NUMERIC (19, 5)
DECLARE @OREMSUBTOTAL NUMERIC (19, 5)
DECLARE @COSTTOTAL NUMERIC (19, 5)
DECLARE @ORCOSTTOTAL NUMERIC (19, 5)

DECLARE @SLPRSNID VARCHAR(15)
DECLARE @SALSTERR VARCHAR(15)
DECLARE @COMMISSIONABLE NUMERIC (19, 5)
DECLARE @ORCOMMISSIONABLE NUMERIC (19, 5)

DECLARE @ALREADYCREATED NUMERIC (19, 5)
DECLARE @ORIGQTY NUMERIC (19, 5)
DECLARE @QTYTOALLOCATE NUMERIC (19, 5)
DECLARE @QTYREMAINING NUMERIC (19, 5)
DECLARE @BATCH VARCHAR(15)
DECLARE @IVACCT INT
DECLARE @IVOFFACCT INT
DECLARE @IVTRXNUMBER VARCHAR(50)
DECLARE @ERRORDESC VARCHAR (255)
DECLARE @NEWLOTNUMBER VARCHAR(21)
DECLARE @LOTQTY NUMERIC (19, 5)
DECLARE @MAXSLTSQNUM INT
DECLARE @DEX_ROW INT
DECLARE @UNITCOST NUMERIC (19, 5)
DECLARE @REMAININGQTY NUMERIC (19, 5)
DECLARE @LOTATRB1 VARCHAR(11)
DECLARE @LOTATRB2 VARCHAR(11)
DECLARE @LOTATRB3 VARCHAR(11)
DECLARE @LOTATRB4 DATETIME
DECLARE @LOTATRB5 DATETIME

DECLARE @MONTH VARCHAR(2)
DECLARE @DAY VARCHAR(2)
DECLARE @YEAR VARCHAR(4)
DECLARE @TODAY DATETIME
DECLARE @NOW DATETIME
DECLARE @HOUR VARCHAR(2)
DECLARE @MINUTE VARCHAR(2)
DECLARE @SECOND VARCHAR(2)
DECLARE @TIME DATETIME
DECLARE @VOIDED INT
DECLARE @QTYPICKED NUMERIC (19, 5)
DECLARE @CWQTYPICKED NUMERIC (19, 5)

DECLARE @tcsFLCU_CW_Display_QTY NUMERIC (19, 5)
DECLARE @tcsFLST_CW_Display_UOfM VARCHAR(9)
DECLARE @UOFM VARCHAR(9)
DECLARE @ENABLEMULTIBIN INT

SELECT @NOW = GETDATE()
SELECT @YEAR = CONVERT(VARCHAR(4), YEAR(@NOW))
SELECT @MONTH = CONVERT(VARCHAR(2), MONTH(@NOW))
SELECT @DAY = CONVERT(VARCHAR(2), DAY(@NOW))
SELECT @TODAY = CONVERT(DATETIME, @YEAR + '-' + @MONTH + '-' + @DAY)

SELECT @HOUR = CONVERT(VARCHAR(2), DATEPART(hh, @NOW))
SELECT @MINUTE = CONVERT(VARCHAR(2), DATEPART(mi, @NOW))

SELECT @SECOND = CONVERT(VARCHAR(2), DATEPART(ss, @NOW))

IF LEN(RTRIM(@HOUR)) = 1
	SET @HOUR = '0' + @HOUR
IF LEN(RTRIM(@MINUTE)) = 1
	SET @MINUTE = '0' + @MINUTE
IF LEN(RTRIM(@SECOND)) = 1
	SET @SECOND = '0' + @SECOND
SELECT @TIME = CONVERT(DATETIME, '1900-01-01 ' + @HOUR + ':' + @MINUTE + ':' + @SECOND + '.000')

SELECT @ENABLEMULTIBIN = ENABLEMULTIBIN FROM IV40100 WHERE SETUPKEY = 1
IF @ENABLEMULTIBIN IS NULL
	SET @ENABLEMULTIBIN = 0

DECLARE CLOSINGCURSOR CURSOR FOR
	SELECT SOPTYPE, SOPNUMBE, DATEREQUESTED, TIMEREQUESTED, USERID FROM ALBWMSPICKCLOSINGQUEUE WHERE [STATUS] = 2 ORDER BY DATEREQUESTED, TIMEREQUESTED

OPEN CLOSINGCURSOR

FETCH NEXT FROM CLOSINGCURSOR INTO @SOPTYPE, @SOPNUMBE, @DATEREQUESTED, @TIMEREQUESTED, @USERID

WHILE @@FETCH_STATUS = 0
	BEGIN
	UPDATE ALBWMSPICKCLOSINGQUEUE SET STATUS = 3, DATEPROCESSSTARTED = @TODAY, TIMEPROCESSSTARTED = @TIME WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND STATUS = 2

	/* ALLOCATE AND CREATE OVERRIDE LOTS */
	DECLARE OVRCURSOR CURSOR FOR
		SELECT LNITMSEQ, CMPNTSEQ, ORIGSLTSQNUM, SERLTNUM, SUM(SERLTQTY) FROM ALBWMS10201 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND VOIDED = 0 
			GROUP BY LNITMSEQ, CMPNTSEQ, ORIGSLTSQNUM, SERLTNUM
			ORDER BY LNITMSEQ, CMPNTSEQ, ORIGSLTSQNUM, SERLTNUM
	
	OPEN OVRCURSOR

	FETCH NEXT FROM OVRCURSOR INTO @LNITMSEQ, @CMPNTSEQ, @ORIGSLTSQNUM, @SERLTNUM, @QUANTITY

	WHILE @@FETCH_STATUS = 0
		BEGIN
		-- @LOTQTY WILL CONTAIN THE QUANTITY (WEIGHT) AUTO-CREATED DUE TO SHORTAGE
		SET @LOTQTY = 0
		SELECT @ORIGQTY = SERLTQTY, @DATERECD = DATERECD, @DTSEQNUM = DTSEQNUM FROM SOP10201 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND SLTSQNUM = @ORIGSLTSQNUM

		SELECT @ALREADYCREATED = ISNULL(SUM(QTYCREATED), 0) FROM ALBWMS10201 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND VOIDED = 0 AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND ORIGSLTSQNUM = @ORIGSLTSQNUM AND IVDOCNBR <> ''

		SET @QTYTOALLOCATE = @QUANTITY - @ORIGQTY - @ALREADYCREATED
			IF @QTYTOALLOCATE > 0 
				BEGIN
				SELECT @ITEMNMBR = ITEMNMBR, @LOCNCODE = LOCNCODE FROM SOP10200 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ

				SELECT @QTYREMAINING = QTYRECVD - QTYSOLD - ATYALLOC, @BIN = BIN, @UNITCOST = UNITCOST FROM IV00300 WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND DATERECD = @DATERECD AND DTSEQNUM = @DTSEQNUM 

				IF @QTYREMAINING < @QTYTOALLOCATE
					BEGIN
					SELECT @IVACCT = IVIVINDX, @IVOFFACCT = IVVARIDX FROM IV00101 WHERE ITEMNMBR = @ITEMNMBR
					SET @BATCH = 'WMS-' + CONVERT(VARCHAR(10), @TODAY, 101)
					SET @NEWLOTNUMBER = SUBSTRING(RTRIM(@SERLTNUM) + 'OR',1,21)
					SET @LOTQTY = @QTYTOALLOCATE - @QTYREMAINING
					EXEC ALB_PROC_CREATE_IV_ADJUSTMENT_TRANSFER 1, @TODAY, @ITEMNMBR, @NEWLOTNUMBER, @LOCNCODE, '', @BIN, '', @LOTQTY, @USERID, @BATCH, @IVACCT, @IVOFFACCT, @UNITCOST, @STATUS OUT, @ERRORDESC OUTPUT, @IVTRXNUMBER OUT
					IF @STATUS = 1
						BEGIN
						EXEC ALB_Post_IV_Transaction 1, @IVTRXNUMBER

						SET @LOTATRB1 = NULL
						SELECT @LOTATRB1 = LOTATRB1, @LOTATRB2 = LOTATRB2, @LOTATRB3 = LOTATRB3, @LOTATRB4 = LOTATRB4, @LOTATRB5 = LOTATRB5 FROM IV00301 WHERE ITEMNMBR = @ITEMNMBR AND LOTNUMBR = @SERLTNUM
						
						IF @LOTATRB1 IS NOT NULL
							BEGIN
							SELECT @COUNT = COUNT(*) FROM IV00301 WHERE ITEMNMBR = @ITEMNMBR AND LOTNUMBR = @NEWLOTNUMBER
							IF @COUNT = 1
								UPDATE IV00301 SET LOTATRB1 = @LOTATRB1, LOTATRB2 = @LOTATRB2, LOTATRB3 = @LOTATRB3, LOTATRB4 = @LOTATRB4, LOTATRB5 = @LOTATRB5 WHERE ITEMNMBR = @ITEMNMBR AND LOTNUMBR = @NEWLOTNUMBER
							ELSE
								INSERT INTO IV00301 (ITEMNMBR, LOTNUMBR, LOTATRB1, LOTATRB2, LOTATRB3, LOTATRB4, LOTATRB5, IUSCOUNT, RCRDSTTS)
								VALUES (@ITEMNMBR, @NEWLOTNUMBER, @LOTATRB1, @LOTATRB2, @LOTATRB3, @LOTATRB4, @LOTATRB5, 1, 1)
							END
													
						SELECT @MAXSLTSQNUM = MIN(SLTSQNUM) FROM SOP10201 WHERE SOPTYPE = 2 AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND SLTSQNUM < 0						
						IF @MAXSLTSQNUM IS NULL
							SET @MAXSLTSQNUM = -1
						ELSE
							SET @MAXSLTSQNUM = @MAXSLTSQNUM - 1

						SET @DEX_ROW = NULL
						SELECT @DEX_ROW = MAX(DEX_ROW_ID) FROM IV00300 WHERE ITEMNMBR = @ITEMNMBR AND LOTNUMBR = @NEWLOTNUMBER AND LOCNCODE = @LOCNCODE AND DATERECD = @TODAY AND QTYRECVD = @LOTQTY AND BIN = @BIN AND LTNUMSLD = 0 AND QTYSOLD = 0 AND ATYALLOC = 0

						IF @DEX_ROW IS NOT NULL
							BEGIN
							--TAKE CARE OF THE EQUIVALENT TCS IV00300							
							INSERT INTO tcsINVTB00020_CW_Lot_Trk (ITEMNMBR, LOCNCODE, QTYTYPE, DATERECD, DTSEQNUM, QTYRECVD, QTYSOLD, ATYALLOC)
							SELECT ITEMNMBR, LOCNCODE, QTYTYPE, DATERECD, DTSEQNUM, 0, 0, 0 FROM IV00300 WHERE DEX_ROW_ID = @DEX_ROW AND
							DTSEQNUM NOT IN (SELECT DTSEQNUM FROM tcsINVTB00020_CW_Lot_Trk TCS WHERE TCS.ITEMNMBR = IV00300.ITEMNMBR AND TCS.LOCNCODE = IV00300.LOCNCODE
								AND TCS.DATERECD = IV00300.DATERECD AND TCS.QTYTYPE = IV00300.QTYTYPE) 													
	
							INSERT INTO SOP10201 ([SOPTYPE],[SOPNUMBE],[LNITMSEQ],[CMPNTSEQ],[QTYTYPE],[SERLTNUM],[SERLTQTY],  [SLTSQNUM],[DATERECD],[DTSEQNUM],[UNITCOST],[ITEMNMBR],[TRXSORCE],[POSTED],[OVRSERLT],[BIN],[MFGDATE],[EXPNDATE])
							SELECT                 @SOPTYPE, @SOPNUMBE, @LNITMSEQ, @CMPNTSEQ,        1,  LOTNUMBR,   @LOTQTY,@MAXSLTSQNUM,  DATERECD,  DTSEQNUM,  UNITCOST,  ITEMNMBR,        '',       0,         0,  BIN,  MFGDATE, EXPNDATE
								FROM IV00300 WHERE DEX_ROW_ID = @DEX_ROW

							UPDATE IV00300 SET LTNUMSLD = 1, ATYALLOC = @LOTQTY WHERE DEX_ROW_ID = @DEX_ROW							

							SELECT @COUNT = COUNT(*) FROM tcsSOPTB00020_CW_SLot_Tk WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SLTSQNUM = @MAXSLTSQNUM
							IF @COUNT = 0
								INSERT INTO tcsSOPTB00020_CW_SLot_Tk (SOPTYPE, SOPNUMBE, LNITMSEQ, QTYTYPE, SLTSQNUM, QUANTITY, UOFM, ACTUALWEIGHT, tcsFLCU_CW_Display_QTY, tcsFLST_CW_Display_UOfM)
								SELECT SOPTYPE, SOPNUMBE, LNITMSEQ, QTYTYPE, @MAXSLTSQNUM, 0, UOFM, @LOTQTY, 0, tcsFLST_CW_Display_UOfM FROM tcsSOPTB00020_CW_SLot_Tk
									WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SLTSQNUM = @ORIGSLTSQNUM
							ELSE
								UPDATE tcsSOPTB00020_CW_SLot_Tk SET QUANTITY = 0, tcsFLCU_CW_Display_QTY = 0, ACTUALWEIGHT = @LOTQTY WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SLTSQNUM = @MAXSLTSQNUM
								
							--ADJUST PICKED LOTS BY REDUCING THE OVERRIDE WEIGHT
							SET @REMAININGQTY = @LOTQTY
							DECLARE WTUPDCURSOR CURSOR FOR 
								SELECT SLTSQNUM, SERLTQTY FROM ALBWMS10201 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND ORIGSLTSQNUM  = @ORIGSLTSQNUM ORDER BY SLTSQNUM DESC 
							
							OPEN WTUPDCURSOR

							FETCH NEXT FROM WTUPDCURSOR INTO @SLTSQNUM, @SERLTQTY
														
							WHILE @@FETCH_STATUS = 0 AND @REMAININGQTY > 0
								BEGIN
								IF @REMAININGQTY > @SERLTQTY
									SET @QTYCREATED = @SERLTQTY
								ELSE
									SET @QTYCREATED = @REMAININGQTY

								UPDATE ALBWMS10201 SET OVRSERLT = 1, IVDOCNBR = @IVTRXNUMBER, QTYCREATED = @QTYCREATED, OVERSLTSQNUM = @MAXSLTSQNUM WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND SLTSQNUM = @SLTSQNUM	

								SET @REMAININGQTY = @REMAININGQTY - @QTYCREATED

								FETCH NEXT FROM WTUPDCURSOR INTO @SLTSQNUM, @SERLTQTY
								END													
							CLOSE WTUPDCURSOR
							DEALLOCATE WTUPDCURSOR	
							END
													
						END
					END
				END

			-- ALLOCATE FROM ORIGINAL LOT ONLY IF AN OVERRIDE LOT WAS NOT CREATED
			--IF @NEWLOTNUMBER = ''
			UPDATE IV00300 SET ATYALLOC = ATYALLOC + (@QTYTOALLOCATE - @LOTQTY) WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND DATERECD = @DATERECD AND DTSEQNUM = @DTSEQNUM AND LOTNUMBR = @SERLTNUM
			
			UPDATE IV00300 SET LTNUMSLD = 1 WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND DATERECD = @DATERECD AND DTSEQNUM = @DTSEQNUM AND LOTNUMBR = @SERLTNUM AND QTYRECVD - QTYSOLD - ATYALLOC = 0
			
			UPDATE IV00102 SET ATYALLOC = ATYALLOC + @QTYTOALLOCATE WHERE ITEMNMBR = @ITEMNMBR AND (LOCNCODE = @LOCNCODE	OR LOCNCODE = '')
			IF @ENABLEMULTIBIN = 1
				UPDATE IV00112 SET ATYALLOC = ATYALLOC + @QTYTOALLOCATE WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND BIN = @BIN			


		FETCH NEXT FROM OVRCURSOR INTO @LNITMSEQ, @CMPNTSEQ, @ORIGSLTSQNUM, @SERLTNUM, @QUANTITY
		END
	CLOSE OVRCURSOR
	DEALLOCATE OVRCURSOR

	/* UPDATE SOP10201 WITH THE PICKED QUANTITY AND EQUIVALENT TCS TABLE WITH CATCHWEIGHT QUANTITY */
	DECLARE PICKLOTCURSOR CURSOR FOR
		SELECT A.LNITMSEQ, A.CMPNTSEQ, A.SLTSQNUM, A.SERLTQTY, A.DATERECD, A.DTSEQNUM, A.BIN, A.ITEMNMBR, B.QUANTITY		
			FROM SOP10201 A LEFT JOIN tcsSOPTB00020_CW_SLot_Tk B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE AND A.LNITMSEQ = B.LNITMSEQ AND A.SLTSQNUM = B.SLTSQNUM 
			WHERE A.SOPTYPE = @SOPTYPE AND A.SOPNUMBE = @SOPNUMBE AND A.SLTSQNUM > 0 
			ORDER BY A.SOPTYPE, A.SOPNUMBE, A.LNITMSEQ, A.CMPNTSEQ, A.SLTSQNUM

	OPEN PICKLOTCURSOR

	FETCH NEXT FROM PICKLOTCURSOR INTO @LNITMSEQ, @CMPNTSEQ, @SLTSQNUM, @QUANTITY, @DATERECD, @DTSEQNUM, @BIN, @ITEMNMBR, @CWQUANTITY
	 
	WHILE @@FETCH_STATUS = 0
		BEGIN
		SELECT @QTYPICKED = ISNULL(SUM(SERLTQTY - QTYCREATED), 0), @CWQTYPICKED = ISNULL(COUNT(SERLTQTY), 0) FROM ALBWMS10201 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND ORIGSLTSQNUM = @SLTSQNUM AND VOIDED = 0		

		SELECT @LOCNCODE = LOCNCODE FROM SOP10200 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ

		-- IF THE QUANTITY PICKED IS ZERO, MUST DEALLOCATE ANY ALLOCATED QUANTITIES. IF THE QUANTITY PICKED IS GREATER THAN ZERO, THE QTY WAS ALREADY ALLOCATED IN THE LOOP ABOVE
		IF @CWQTYPICKED = 0
			BEGIN
			IF @QUANTITY > 0
				BEGIN
				UPDATE SOP10201 SET SERLTQTY = 0 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND SLTSQNUM = @SLTSQNUM

				UPDATE IV00300 SET ATYALLOC = ATYALLOC - @QUANTITY, LTNUMSLD = 0 WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND DATERECD = @DATERECD AND DTSEQNUM = @DTSEQNUM
						
				UPDATE IV00102 SET ATYALLOC = ATYALLOC - @QUANTITY WHERE ITEMNMBR = @ITEMNMBR AND (LOCNCODE = @LOCNCODE	OR LOCNCODE = '')
				IF @ENABLEMULTIBIN = 1
					UPDATE IV00112 SET ATYALLOC = ATYALLOC - @QUANTITY WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND BIN = @BIN			
												
				END

			-- REMOVE ANY EXISTING SPLITS
			DELETE tcsSOPTB00020_CW_Split WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SEQNUMBR = @SLTSQNUM
			
			END

		IF @QTYPICKED <> @QUANTITY
			BEGIN
			UPDATE SOP10201 SET SERLTQTY = @QTYPICKED WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ AND SLTSQNUM = @SLTSQNUM
			END					

		IF @CWQTYPICKED <> @CWQUANTITY
			BEGIN
			UPDATE tcsSOPTB00020_CW_SLot_Tk SET QUANTITY = @CWQTYPICKED, tcsFLCU_CW_Display_QTY = @CWQTYPICKED WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SLTSQNUM = @SLTSQNUM				
			UPDATE tcsINVTB00020_CW_Lot_Trk SET ATYALLOC = ATYALLOC + (@CWQTYPICKED - @CWQUANTITY) WHERE ITEMNMBR = @ITEMNMBR AND DATERECD = @DATERECD AND DTSEQNUM = @DTSEQNUM 
			-- THE LINE BELOW IS NOT NECESSARY BECAUSE TCW ALREADY HAS A TRIGGER ON tcsSOPTB00020_CW_Track that takes care of allocating/deallocating QTY at the site level
			--UPDATE tcsINVTB00020_CWUOMSite SET ATYALLOC = ATYALLOC + (@CWQTYPICKED - @CWQUANTITY) WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE
			IF @ENABLEMULTIBIN = 1
				UPDATE tcsINVTB00020_CW_BT SET ATYALLOC = ATYALLOC + (@CWQTYPICKED - @CWQUANTITY) WHERE ITEMNMBR = @ITEMNMBR AND LOCNCODE = @LOCNCODE AND BIN = @BIN				
			END
		FETCH NEXT FROM PICKLOTCURSOR INTO @LNITMSEQ, @CMPNTSEQ, @SLTSQNUM, @QUANTITY, @DATERECD, @DTSEQNUM, @BIN, @ITEMNMBR, @CWQUANTITY
		END
	CLOSE PICKLOTCURSOR
	DEALLOCATE PICKLOTCURSOR

	/* ADD PICKED CASES TO TCW BREAKDOWN TABLE */
	DECLARE PICKLOTCURSOR CURSOR FOR
		SELECT LNITMSEQ, CMPNTSEQ, ORIGSLTSQNUM, SLTSQNUM, SERLTQTY, QTYCREATED, VOIDED FROM ALBWMS10201 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE ORDER BY SOPTYPE, SOPNUMBE, LNITMSEQ, CMPNTSEQ, SLTSQNUM

	OPEN PICKLOTCURSOR

	FETCH NEXT FROM PICKLOTCURSOR INTO @LNITMSEQ, @CMPNTSEQ, @ORIGSLTSQNUM, @SLTSQNUM, @QUANTITY, @QTYCREATED, @VOIDED
	 
	WHILE @@FETCH_STATUS = 0
		BEGIN
		IF @VOIDED = 1
			DELETE FROM tcsSOPTB00020_CW_Split WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SEQNUMBR = @SLTSQNUM
		ELSE
			BEGIN
			SELECT @COUNT = COUNT(*) FROM tcsSOPTB00020_CW_Split WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SEQNUMBR = @SLTSQNUM
			IF @COUNT = 0
				INSERT INTO tcsSOPTB00020_CW_Split (SOPTYPE, SOPNUMBE, LNITMSEQ, SEQNUMBR, QUANTITY)
				VALUES (@SOPTYPE, @SOPNUMBE, @LNITMSEQ, @SLTSQNUM, @QUANTITY)       
			ELSE
				UPDATE tcsSOPTB00020_CW_Split SET QUANTITY = @QUANTITY WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND SEQNUMBR = @SLTSQNUM
			END 

		FETCH NEXT FROM PICKLOTCURSOR INTO @LNITMSEQ, @CMPNTSEQ, @ORIGSLTSQNUM, @SLTSQNUM, @QUANTITY, @QTYCREATED, @VOIDED
		END
	CLOSE PICKLOTCURSOR
	DEALLOCATE PICKLOTCURSOR
	

	/* ADJUST SOP LINES AND REMOVE QTY FOR LOTS NOT PICKED */	
	DECLARE PICKLINECURSOR CURSOR FOR
		SELECT LNITMSEQ, CMPNTSEQ, QTYPICKED, CWQTYPICKED, QTYREMAI, CWQTYREMAI, LOCNCODE, ITEMNMBR FROM ALBWMS10200 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE
	
	OPEN PICKLINECURSOR
	
	FETCH NEXT FROM PICKLINECURSOR INTO @LNITMSEQ, @CMPNTSEQ, @QUANTITY, @CWQUANTITY, @QTYREMAI, @CWQTYREMAI, @LOCNCODE, @ITEMNMBR

	WHILE @@FETCH_STATUS = 0
		BEGIN		
			BEGIN TRY
				BEGIN TRANSACTION
					UPDATE SOP10200 SET QUANTITY = @QUANTITY, QTYREMAI = @QUANTITY, QTYTOINV = @QUANTITY, ATYALLOC = @QUANTITY, QTYFULFI = @QUANTITY, QTYSLCTD = @QUANTITY, QTYTBAOR = 0, ITEMCODE = 'PICKED', XTNDPRCE = ROUND(UNITPRCE * @QUANTITY,2), OXTNDPRC = ROUND(ORUNTPRC * @QUANTITY,2), REMPRICE = ROUND(UNITPRCE * @QUANTITY,2), OREPRICE = ROUND(ORUNTPRC * @QUANTITY,2), EXTDCOST = ROUND(UNITCOST * @QUANTITY,2), OREXTCST = ROUND(ORUNTCST * @QUANTITY,2) 
						WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ AND CMPNTSEQ = @CMPNTSEQ 	

					UPDATE tcsSOPTB00020_CW_Track SET QUANTITY = @CWQUANTITY, tcsFLCU_CW_Display_QTY = @CWQUANTITY, ACTUALWEIGHT = @QUANTITY WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND LNITMSEQ = @LNITMSEQ
				COMMIT
			END TRY
			BEGIN CATCH
				ROLLBACK
			END CATCH
		FETCH NEXT FROM PICKLINECURSOR INTO @LNITMSEQ, @CMPNTSEQ, @QUANTITY, @CWQUANTITY, @QTYREMAI, @CWQTYREMAI, @LOCNCODE, @ITEMNMBR
		END
	CLOSE PICKLINECURSOR
	DEALLOCATE PICKLINECURSOR
		
	--UPDATE SOP HEADER SUBTOTALS
	SET @SUBTOTAL = NULL
	SELECT @SUBTOTAL = SUM(XTNDPRCE), @ORSUBTOTAL = SUM(OXTNDPRC), @REMSUBTOTAL = SUM(REMPRICE), @OREMSUBTOTAL = SUM(OREPRICE), @COSTTOTAL = SUM(EXTDCOST), @ORCOSTTOTAL = SUM(OREXTCST) FROM SOP10200 WHERE SOPTYPE = @SOPTYPE  AND SOPNUMBE = @SOPNUMBE	
	IF @SUBTOTAL IS NOT NULL
		BEGIN
			BEGIN TRY
				BEGIN TRANSACTION
					UPDATE SOP10100 SET CMMSLAMT = @SUBTOTAL, ORCOSAMT = @ORSUBTOTAL, SUBTOTAL = @SUBTOTAL, ORSUBTOT = @ORSUBTOTAL, REMSUBTO = @REMSUBTOTAL, OREMSUBT = @OREMSUBTOTAL, EXTDCOST = @COSTTOTAL, OREXTCST = @ORCOSTTOTAL WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE

					UPDATE SOP10100 SET DOCAMNT = SUBTOTAL + MISCAMNT + FRTAMNT + TAXAMNT - TRDISAMT, ORDOCAMT = ORSUBTOT + ORMISCAMT + ORTAXAMT - ORTDISAM,	
						ACCTAMNT = (SUBTOTAL + MISCAMNT + FRTAMNT + TAXAMNT - TRDISAMT) - PYMTRCVD,
						ORACTAMT = (ORSUBTOT + ORMISCAMT + ORTAXAMT - ORTDISAM) - ORPMTRVD
						WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE  
				COMMIT				
			END TRY
			BEGIN CATCH
				ROLLBACK
			END CATCH		
		END

	--UPDATE COMMISSION RECORDS
	DECLARE PICKCOMMCURSOR CURSOR FOR
		SELECT SLPRSNID, SALSTERR, SUM(XTNDPRCE), SUM(OXTNDPRC) FROM SOP10200 
			WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE 
			GROUP BY SLPRSNID, SALSTERR

	OPEN PICKCOMMCURSOR
	
	FETCH NEXT FROM PICKCOMMCURSOR INTO @SLPRSNID, @SALSTERR, @COMMISSIONABLE, @ORCOMMISSIONABLE
			
	WHILE @@FETCH_STATUS = 0
		BEGIN
		UPDATE SOP10101 SET ACTSLAMT = @COMMISSIONABLE, ORSLSAMT = @ORCOMMISSIONABLE, CMMSLAMT = @COMMISSIONABLE, ORCOSAMT = @ORCOMMISSIONABLE 
			WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND SALSTERR = @SALSTERR AND SLPRSNID = @SLPRSNID
			
		FETCH NEXT FROM PICKCOMMCURSOR INTO @SLPRSNID, @SALSTERR, @COMMISSIONABLE, @ORCOMMISSIONABLE
		END
	CLOSE PICKCOMMCURSOR
	DEALLOCATE PICKCOMMCURSOR
	
	UPDATE ALBWMS10100 SET [STATUS] = 2, STATDATE = @TODAY, STATTIME = @TIME, ENDDATE = @TODAY, ENDTIME = @TIME WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE		
	
	DELETE ALBWMSPICKCLOSINGQUEUE WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SOPNUMBE AND STATUS = 3
	
	FETCH NEXT FROM CLOSINGCURSOR INTO @SOPTYPE, @SOPNUMBE, @DATEREQUESTED, @TIMEREQUESTED, @USERID
	END
CLOSE CLOSINGCURSOR
DEALLOCATE CLOSINGCURSOR


